name: Testing

on:
  push:
    tags:
      - 'testing/*'


jobs:

  linux:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.16.3

    - name: Set build variables
      run: echo "revision=${GITHUB_REF##*/}" >> ${GITHUB_ENV}

    - name: Initialise build environment
      run: yarn install

    - name: Build release for linux64
      run: yarn gulp release --linux64

    - name: Move artifacts
      run: mv release/rotorflight-blackbox* .

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: rotorflight-blackbox-linux-testing-${{ env.revision }}
        path: rotorflight-blackbox*


  macos:

    runs-on: macos-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.16.3

    - name: Set build variables
      run: echo "revision=${GITHUB_REF##*/}" >> ${GITHUB_ENV}

    - name: Initialise build environment
      run: yarn install

    - name: Build release for MacOS
      run: yarn gulp release --osx64

    - name: Move artifacts
      run: mv release/rotorflight-blackbox* .

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: rotorflight-blackbox-macos-testing-${{ env.revision }}
        path: rotorflight-blackbox*


  windows:

    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.16.3

    - name: Set build variables
      run: |
        $snapshot = $env:GITHUB_REF -replace '.*/',''
        echo "revision=$snapshot" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    - name: Initialise build environment
      run: yarn install

    - name: Build release for windows
      run: yarn gulp release --win64

    - name: Move artifacts
      run: move release/rotorflight-blackbox* .

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: rotorflight-blackbox-windows-testing-${{ env.revision }}
        path: rotorflight-blackbox*


  cleanup:

    runs-on: ubuntu-latest

    needs: [linux, windows, macos]

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Delete tag
      run: git push origin :${GITHUB_REF}

